name: Download YouTube MP3

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'YouTube link'
        required: true

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install yt-dlp and ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install --upgrade pip
          pip install yt-dlp

      - name: Debug and Download
        run: |
          echo "Downloading from: ${{ github.event.inputs.url }}"
          yt-dlp --version
          ffmpeg -version
          yt-dlp -x --audio-format mp3 "${{ github.event.inputs.url }}"

      - name: Upload MP3 file
        uses: actions/upload-artifact@v3
        with:
          name: youtube-mp3
          path: "*.mp3"
